version: '3.8'

services:
  bot:
    image: ghcr.io/vyasma-mafia/mafia-itmo-event-manager-bot:main
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:///data/db.sqlite3
    restart: always
