version: '3.8'

services:
  bot:
    # image: ghcr.io/vyasma-mafia/mafia-itmo-event-manager-bot:main
    build: .
    env_file:
      - .env
      - pg.env
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:alpine
    env_file:
      - pg.env
    ports:
      - "5433:5433"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always
